version: "2.1"
services:
  postgres:
    image: postgres
    container: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=contact
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
